/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import formBuilder from "../../src/plugins/form-builder/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "form-builder": formBuilder,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    meilisearch: meilisearch,
  },
});
